8.9. Desafio: usando a exception NegocioException